server:
  port: 8070

connect:
  mqtt:
    endpoint: 'tcp://106.75.50.110:1883'
    # 链接超时时间，秒
    connectionTimeout: 10
    # 心跳保持，秒
    keepAliveTime: 60

gateway:
  pk: 'driver_001'
  devId: 'driver_test001'
  devSecret: '311e9707469241938e08f6d64a55b157'

http:
  server:
    port: 8070
  client:
    connect:
      host: "http://localhost:8070"
      aid: "test"
      key: "111111"

tcp:
  client:
    connect:
      ip: 192.168.50.212
      port: 8080
  server:
    port: 7070


tio:
  core:
    server:
      # websocket port default 9876
      port: 7000
      # 心跳时间
      heartbeat-timeout: 30000
      # 监控时段,多个之间用逗号隔开
      ip-stat-durations: [ 60 ]
    # 集群配置 默认关闭
    cluster:
      enabled: false
      # 集群是通过redis的Pub/Sub实现，所以需要配置Redis
      redis:
        ip: 127.0.0.1
        port: 6379
      all: true
      group: true
      ip: true
      user: true
      # SSL 配置
      ssl:
        enabled: false
        key-store:
        password:
        trust-store:
