server:
  port: 8070

connect:
  mqtt:
    endpoint: 'tcp://106.75.50.110:1883'
    # 链接超时时间，秒
    connectionTimeout: 10
    # 心跳保持，秒
    keepAliveTime: 60

gateway:
  pk: 'b6e2cc8aaf6c4255a15106d4806cd7ec'
  devId: 'demo_gateway'
  devSecret: 'ae0122eeb6cd48e4b10405d04987946f'

# 日志配置
logging:
  level.root: INFO
  file: logs/iotos-soft-gateway.log
  pattern:
    file: '%date{"yyyy-MM-dd HH:mm:ss.SSS"} %-5level [%thread] %logger{128}.%M:%line - %msg %n'
    console: '%date{"yyyy-MM-dd HH:mm:ss.SSS"} %-5level [%thread] %logger{128}.%M:%line - %msg %n'
  charset:
    console: UTF-8
    file: UTF-8
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      clean-history-on-start: true
      max-file-size: '500mb'
      max-history: 7