server:
  port: 8080

connect:
  mqtt:
    endpoint: 'tcp://iotos-demo.hekr.me:1883'
    #    endpoint: 'tcp://dev100:1883'

    # 链接超时时间，秒
    connectionTimeout: 10
    # 心跳保持，秒
    keepAliveTime: 60
    # 集群模式 standalone 单机模式，不允许多个客户端登录
    # cluster 集群模式，允许多个客户端同时登录，但是下发的消息只有1个客户端可以收到
    # broadcast 广播模式，允许多个客户端同时登录，下发的消息所有客户端可以收到；
    cluster.mode: standalone
    # 否本地数据发生变化才发送数据; true 数据变化才发送； false 直接发送
    data:
      changed: true
      full:
        # 全量发送的时候命令
        cmd: report
        # 全量数据发送间隔； 小于等于0不发送; 单位秒； 建议配合 changed 用。 如果配置了 changed，则发送间隔建议设置为300（5分钟）
        interval: 300
spring:
  main:
    allow-circular-references: true

gateway:
  pk: 'b6e2cc8aaf6c4255a15106d4806cd7ec'
  devId: 'du_gateway'
  devSecret: '0abcbe87d37d4e5d9da07fae5856277f'

